### ISSUE TITLE
Server side pagination and sorting vs client side pagination and sorting

### ISSUE THREAD

**Issue by mbury** [sematext/sematable#1]
Hi, I wonder where is the limit of use of filtering and pagination in your browser? When the data set is too large to load it into client browser? Do you experiment with such limit during development of this library?

**Comment by amir-hadzic** [comment]
Hello.

I think it depends on your app and use cases, but sematable was developed for small datasets in mind. If you have more data than can fit in the browser, or maybe it's simply too slow for the user to wait for all data to load, you would probably want to use server-side pagination, sorting, and filtering. But then you really don't have any reason to use sematable (that's primarily what it does).

**Comment by otisg** [comment]
@mbury hope this answers your question.  Please reopen if you have more.

**Comment by aftabnaveed** [comment]
@amir-hadzic you have a point, but semtable is easy to setup and use. If someone wants to customize pagination and load data from the server is there a way to do it?
