### ISSUE TITLE
AppsTableActions component doesn't render a working Link 

### ISSUE THREAD

**Issue by pepepaco** [sematext/sematable#10]
Hello i'm trying to implement the Action example but the Link doesn't render as a working link, could you please provide a working example of the actions column?

thanks.

**Comment by amir-hadzic** [comment]
Hello.

The example from readme uses react-router's Link, so maybe that's causing issues for you? You can use any JSX in column components, so you can just use <a> if you want regular links:

```javascript
class AppsTableActions extends Component {
  render() {
    const row = this.props.row;
    return (
      <a href={`/settings/${row.id}`}>
        Settings
      </a>
    );
  }
}
```

**Comment by pepepaco** [comment]
wow ok, thank you!
