### ISSUE TITLE
A couple of questions on using Bootstrap 3 and editable fields

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#16]
Can one use Bootstrap 3 with sematable? 
Are editable fields allowed within columns?

**Comment by amir-hadzic** [comment]
Hello,

> Can one use Bootstrap 3 with sematable?

We haven't tested it with Bootstrap 3, but I think it should be fine since we haven't really used any Bootstrap 4 specific classes. Give it a spin and let us know :)

> Are editable fields allowed within columns?

Yes, you can specify a custom component for any column, so you can provide your own `EditableField` component.

**Comment by pgoldweic** [comment]
Thanks! I'll give it a try.

**Comment by otisg** [comment]
Should we close this one, @pgoldweic , considering you had success with Bootstrap 4?

**Comment by pgoldweic** [comment]
Yes, I think we should close this one. Thanks!
