### ISSUE TITLE
Unable to use sematable (errors at table initialization time)

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#17]
I have tried using sematable but I get errors from your library when it tries to initialize the table, even though I've pretty sure I've passed in all the (at least documented) parameters.
The error is as follows:
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at selectors.js:179
    at index.js:65
    at index.js:27
    at Object.selector [as getFilterOptions] (index.js:76)
    at Connect.mapStateToProps [as finalMapStateToProps] (sematable.js:110)
    at Connect.computeStateProps (connect.js:146)
    at Connect.updateStatePropsIfNeeded (connect.js:204)
    at tryCatch (connect.js:64)
    at Connect.handleChange (connect.js:291)
    at Connect.trySubscribe (connect.js:240)
And it is printed out in the console right after the action 'sematable/TABLE_INITIALIZE' is logged by the logger. 
Aside from this problem, I would strongly suggest that you include a *complete* example of use of sematable in a third party app. Perhaps this may clarify some misunderstandings about the component's requirements (I believe the current documentation is helpful but not complete. E.g. it does not explain clearly what props should look like) that may help resolve this problem. 
Thanks!

**Comment by amir-hadzic** [comment]
Hello,

Thanks for the suggestions, we'll try to improve the documentation.

Can you please include a code example/test case that causes this issue?

**Comment by pgoldweic** [comment]
Hi, I've made some progress, although this time using the 'advanced usage' instructions. Unfortunately I've concluded that the code does not play well with react-bootstrap (which is bootstrap 3), so I may have to look for alternatives to your component, since I do not have much time to experiment. 
BTW, I'd like to point out two typos/mistakes in your documentation:
1- In the instructions to create one's reducer, it should say 'combineReducers' instead of 'combineReducer' as the method name.
2- In the advanced usage instructions, the 'columns' variable should be defined as an array, and not as an object. That is, if I use the object instead of the array -which is used in the 'regular' instructions-, then I get an error message of the sort: columns.forEach is NOT a function. After changing columns to become an array just like before, then my code works (except styles, likely due to the Bootstrap 3 incompatibility). Here's a little screenshot of how my table looks, using the react-bootstrap 'Table' component:

![image](https://cloud.githubusercontent.com/assets/155515/22167579/f007a000-df2c-11e6-9344-6f79952755ad.png)

**Comment by pgoldweic** [comment]
I've decided to  give it a try with Bootstrap 4 styles, and I get a basic table (with no actions) working, following the 'advanced usage' instructions with the comments above (good news!). However, I add another column to the table which contains (in each row) a couple of buttons, each of them modifying the table state on click. My problem seems to be that, right after the state modification action gets executed, the whole table is re-mounted (which unfortunately clears the state changes obtained from pressing the buttons, as the page gets reloaded :-(). 
Can you tell why this could be happening, or whether this is something you would have expected? Thanks!

**Comment by otisg** [comment]
Thanks for reporting documentation errors.  I fixed 1).  @amir-hadzic could you please fix 2)?

**Comment by amir-hadzic** [comment]
Hello,

Thanks for catching the error in `columns`, it should be fixed now.

> My problem seems to be that, right after the state modification action gets executed, the whole table is re-mounted (which unfortunately clears the state changes obtained from pressing the buttons, as the page gets reloaded :-(). Can you tell why this could be happening, or whether this is something you would have expected? Thanks!

That does sound odd, do you see any errors in the console when that happens? If you log redux actions in your app, do you see a lot of `TABLE_INITIALIZE` actions? If yes, are you calling `sematable()` in your render function?

If you can post the full code example, that would help very much as well.

**Comment by pgoldweic** [comment]
Thanks for following up on this. Actually, the page appears to fully reload  (after the expected action gets executed when clicking on a button), and therefore, the console gets cleared up and the top-level component gets mounted again ( only one TABLE_INITIALIZE action is then logged, together with my own initialization action ). 
I would include my full code but it's quite long :-(. However, I've just discovered something that might have resolved the issue: I added an 'event.preventDefault()' call to the button click handlers (this is now called right after the original event handler gets called). Without this extra call, the buttons were producing the same behavior I described -although now only in Firefox!- while after the extra call, both Chrome and Firefox exhibit correct behavior (no re-mounting/reloading of the page).  I assume there must be a good reason for this even though I can't yet explain it (I am still a React/Redux newbie, as you may realize).

**Comment by amir-hadzic** [comment]
Ahh, I see, I was thinking that only the table component gets mounted again. I think you might have used `<button>` without `type="button"`. The default behavior for HTML button is to submit unless you `preventDefault()` or specify `type="button"`.

I'm glad you got it to work! I'm assuming that we can now close this issue?

**Comment by pgoldweic** [comment]
Oh, I see. I actually used the Button component from 'reactstrap' (that is, Bootstrap 4 components for React), but perhaps it shares behavior with the HTML 'button'.... Interestingly, at some point, the unfortunate behavior was happening only on Firefox (and not in Chrome). 
Feel free to close this issue though. Thanks!

**Comment by godd9170** [comment]
Just as an FYI for anyone who ends up here by searching the `forEach` error. I implemented the code in the README expecting it to just render out of the box. I unfortunately however forgot to pass a `data` prop into the exported `AppsTable`. No react PropTypes warnings fired so I wasn't immediately thinking that was the issue.
