### ISSUE TITLE
no default way of displaying the search filter unless using Table component?

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#19]
After my experimentation with the 'advanced usage' instructions, I am able to produce the following table using reactstrap (Bootstrap 4 components):

![sematable](https://cloud.githubusercontent.com/assets/155515/22269111/ab249f1c-e24f-11e6-99f3-624ce9cb33b4.png)

However, the problem seems to be that the search/filter component is not displaying appropriately. Note that I have not defined any particular filters, but it would be nice to get the text search behavior though (I've defined some of the columns as 'searchable'), but I am not sure how, given that I am not using the sematable 'Table' component. Any suggestions?

**Comment by amir-hadzic** [comment]
Hello,

I think this is caused by react-select css not being loaded. You need to make sure that you load the react-select css. I'm not sure how you are loading css in your application, but you should have react-select css in `node_modules/react-select/dist/react-select.css`.

Sorry for not pointing this out in the documentation, I'll fix that!

**Comment by amir-hadzic** [comment]
Fixed the documentation, this is now in the Getting Started part of the readme.

**Comment by pgoldweic** [comment]
Yes, that definitely does it. Thanks!

**Comment by pgoldweic** [comment]
Sorry for closing too soon. How do I ensure that font-awesome is already loaded too? I don't see it in the node-modules folder. Is this expected? (or perhaps nothing else other than react-select is needed?).

**Comment by amir-hadzic** [comment]
I've noticed that font-awesome is not listed in dependencies today and fixed it. If you use the latest release (v1.3.1) and run `npm install` again, you should see font-awesome in node_modules.

**Comment by pgoldweic** [comment]
Great! Thanks again. Closing issue now.
