### ISSUE TITLE
page size choice  not displaying correctly when 'All' is chosen

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#21]
I've noticed that when changing the table's size to show 'All' of the elements, the display reads 'All false somenumber' , instead of the expected 'All of somenumber'. In other words, the 'of' word seems to be replaced incorrectly by 'false' when choosing the 'All' option (all other options display 'of' instead).

**Comment by mbonaci** [comment]
Thanks for reporting this, my bad.
Fixed (hopefully) :)
