### ISSUE TITLE
Add support for tags in filters

### ISSUE THREAD

**Issue by amir-hadzic** [sematext/sematable#3]
User must be able to filter the table by selecting predefined tags in the filter. By default, the tags must be generated from the provided data by taking unique values for each column that is marked as taggable.

The tags must be auto-completed while user is typing, and the tags should be displayed in the form of "ColumnName:TagValue".

 * User must still be able to use the filter for free form text search.
 * Developer must specify that a column is taggable by setting `taggable: true` in the column definition.
 * Developer must be able to programmatically add or remove tags from the filter.
 * Developer should be able to override the available tags for each column by defining `tags: ['value1', 'value2']` in the column definition.
 * Developer should be able to provide a class name for each distinct tag value so it's possible to customize how the tag is displayed in the filter dropdown.

**Comment by otisg** [comment]
"taggable" may not be the most intuitive word choice here.  It implies one can add tags, but this is really about filtering by column value, not tagging.  Unfortunately, don't have a better suggestion right now.

**Comment by amir-hadzic** [comment]
Yeah, I'm bugged by it as well. I'll think about other naming options when I'm done with the implementation.

**Comment by mbonaci** [comment]
In the jQuery world, they used to call those tags `tokens`, but maybe that makes even less sense, esp. in our context.
Perhaps more useful name would be `pill` (`column-pills`), which is what Bootstrap calls tags that are rounded.
After looking at all these options, to me `column-tags` still sounds best.

**Comment by otisg** [comment]
This is about *filtering* by column value, so filterable would be a better name.

**Comment by amir-hadzic** [comment]
We already have `filterable: true|false` for the text filter. So maybe we should have `textFilterable`, and `valueFilterable`?

**Comment by otisg** [comment]
I assumed the existing option was more about "search", because the matching is a little lose (any substring, right?), while "filter" could imply "exact match".

I was going to suggest an alternative -- suggestible -- but that actually means "easily influenced" in English.  My thinking was that columns marked as such would be the ones that can be suggested in the filter field...

**Comment by amir-hadzic** [comment]
Ok, I've made some changes, and we now use:

- `searchable: true|false` to indicate that a column should be searchable by text
- `filterable: true|false` to indicate that a column should be filterable by distinct column values
- `filterValues: [v1, v2]` to optionally provide predefined list of column values (by default we take unique values from available data)
- `getFilterTitle: func(value)` to optionally provide a function for returning title text that should be shown when related filter option is hovered (no title by default)
- `getFilterLabel: func(value)` to optionally provide the label text we should use for the provided filter value (by default we use `columnName:columnValue`)
- `getFilterClassName: func(value)` to optionally provide a css class that should be applied to filter option for the provided filter value
