### ISSUE TITLE
Hide per-page element if number of rows is smaller than the smallest option in the pulldown

### ISSUE THREAD

**Issue by otisg** [sematext/sematable#35]
![sematable-rows-per-page](https://cloud.githubusercontent.com/assets/332580/23524467/bf6e727e-ff58-11e6-9ab2-b607ad95e635.png)

**Comment by gor181** [comment]
The easiest approach here would be not to render the `of N` at all as now we have two behaviours:

In case when `All` is selected:
![image](https://cloud.githubusercontent.com/assets/8964589/23529429/ddfbf6f4-ff9d-11e6-8765-ed46a2c619fc.png)

In case when any other value is selected:
![image](https://cloud.githubusercontent.com/assets/8964589/23529436/e72de6ce-ff9d-11e6-8641-7cf19cc3df21.png)

Usually information of how many results have been fetched or exist in table are set in table footer aligned right, something as `Showing N of N`.

@amir-hadzic Do you think we can just remove this?

**Comment by gor181** [comment]
@amir-hadzic I attached the PR, so in case you find my suggestion as suitable feel free to merge it in.

**Comment by otisg** [comment]
Why not move it to bottom-right as you suggested?
![table-gw](https://cloud.githubusercontent.com/assets/332580/23530562/3b7e6268-ff70-11e6-9931-7807bbd1b4fe.png)
![table-ga](https://cloud.githubusercontent.com/assets/332580/23530563/3b7ff268-ff70-11e6-8150-c98f7071a550.png)

**Comment by gor181** [comment]
Yap, we can make it as in Google Webmaster. Will rework it. Thanks
