### ISSUE TITLE
header tooltips are not working

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#37]
Sorry for creating a new issue on this. Not sure whether you are following comments on closed issues (issue #24), so I decided to create a new one. But feel free to merge this issue into the other one if appropriate.  As I explained there, the fix you had applied a week ago did not work for me. Please see my comments in (now closed) issue #24.

**Comment by amir-hadzic** [comment]
Hi @pgoldweic,

The issue was that we didn't copy the title property from column definitions into header props. I've added a fix so the title is now included in header props as well.

**Comment by pgoldweic** [comment]
Thanks for doing that. However, I have to say that this feature is only working with column titles, and not the header titles. In other words, if I add a title to the headers, it does not work unless I also add the title to the columns (I did bump the version to 1.4.4). Would be useful to have clear documentation on it.
