### ISSUE TITLE
problem trying to use Sematable

### ISSUE THREAD

**Issue by JOSECCZ** [sematext/sematable#41]
[sematable-master.zip](https://github.com/sematext/sematable/files/846121/sematable-master.zip)
[sematable-master.zip](https://github.com/sematext/sematable/files/846122/sematable-master.zip)

Hello
   I am trying to use Sematable but I got the next error:

npm run storybook

> sematable@1.4.4 storybook C:\Users\jcabrerazuniga\Documents\play\sematable-master
> BOOTSTRAP_VERSION=4.0.0 start-storybook -p 6006

'BOOTSTRAP_VERSION' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "storybook"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sematable@1.4.4 storybook: `BOOTSTRAP_VERSION=4.0.0 start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sematable@1.4.4 storybook script 'BOOTSTRAP_VERSION=4.0.0 start-storybook -p 6006'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sematable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BOOTSTRAP_VERSION=4.0.0 start-storybook -p 6006
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sematable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sematable
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jcabrerazuniga\Documents\play\sematable-master\.storybook\npm-debug.log

I was able to get all the node related modules to compile the js programs and a lib folder was created with "normal" java script files. Yet, I can't run your sample. 

Can you please give me an idea about what/how this is happening?

**Comment by amir-hadzic** [comment]
Hello,

I've pushed a fix for this, so it should work if you pull and try again. Environment variable in script command doesn't work Windows.

Let me know if it still doesn't work.
