### ISSUE TITLE
Does sematable support the creation of multiple tables in one app?

### ISSUE THREAD

**Issue by pgoldweic** [sematext/sematable#43]
I need to create an arbitrary number of tables that is known dynamically during the app's runtime.  How do I go about creating different sematable instances for these tables? (Is this supported by sematable in the first place?)
Thanks!

**Comment by otisg** [comment]
Maybe you could give it a try and report issues if you have any?

**Comment by pgoldweic** [comment]
The point is that I don't how to try it, other than statically define a wrapper component for each of my tables (as far as I understand, I need to have a statement like 'export default sematable("tableName", MyComponent, columns, config)'  in my wrapper definition -assuming that MyComponent is such a wrapper definition- for every table), which certainly is not possible -or desirable- if one doesn't know how many tables will be needed.

**Comment by gor181** [comment]
Hey @pgoldweic,

Sematable is actually using `tableName` as a namespace in the `sematable` reducer therefore you can create `N` tables just by rendering the component. Once the component is initialised it will fire an action which will set the initial state for the new table in the reducer.

Do you have some specific approach in mind on how you would like to dynamically generate tables?

**Comment by mbonaci** [comment]
That first param is used to key table's state in the Redux state tree, under `sematable`.
So, if you don't care about that name you could simply use a random string or some UUID (e.g. https://www.npmjs.com/package/uuid).
Would that work?

**Comment by pgoldweic** [comment]
Thanks @gor181 and @mbonaci for your answers. But, assuming the table name is used as an index in sematable's state, doesn't that mean that all my tables -which would be instances of the same wrapper- would be sharing the same index in the sematable reducer?  Or perhaps the table name is used by sematable as a prefix to a larger name managed internally by sematable? 
In terms of how the tables would be dynamically generated, I'm afraid I still have to figure this out. I was hoping that each table would go in a client route (note: I haven't experimented with routing yet) but I'm not sure the routes can be dynamically defined.

**Comment by gor181** [comment]
As long the tableName is unique your data is safe from mutation, meaning that each table is going to have it's own state tree so there is no sharing.
As @mbonaci suggested, you can use `uuid` if you are going to create those tables on the fly.

**Comment by pgoldweic** [comment]
So I think I'm understanding that I actually need to call 'sematable(tablename, MyComponent, config)' for each of my tables, although with a different table name parameter (as I had suspected). But then, this clashes with my understanding of how I need to define MyComponent. Currently I have it in its own page, and at the end of the file, there's a statement that reads: 'export default sematable("tableName", MyComponent, columns, config)'. If I am going to create different tables with different names, it follows that I will need to call the sematable method several times from some *other* component that is in charge of rendering the tables, but then, MyComponent and this other component need to be defined in the same file -as I won't be able to statically export any of them-,  am I correct? 
Sorry to sound silly  but I'm still a newbie with react/redux/ES6 :-(

**Comment by gor181** [comment]
> So I think I'm understanding that I actually need to call 'sematable(tablename, MyComponent, config)' for each of my tables, although with a different table name parameter (as I had suspected). 

correct

Just a question. Usually table configurations (data, columns) are never identical but only when you actually want to show the same table on some other place/page. 
So what's your end goal? Reusing MyComponent with different columns, data and potentially config? As I do not see much benefit in that.

So in a scenario where you would have an API which would return dynamically computed pages with a lot of tables (tableName, columns, data) you could create a simple react component, ex:

```
import sematable, { Table } from 'sematable';

class MyComponent extends Component {
  render() {
    return (
      <Table {...this.props} />
    );
  }
}

class MyComponentExtended extends Component {
  render() {
    return (
      <Table {...this.props} />
    );
  }
}

export default class GenericTable extends React.Component {
  render() {
    const { tableName, columns, data, config, type } = this.props;

    const typeToComponent = {
      myComponent: MyComponent,
      myComponentExtended: MyComponentExtended,
    };
    
    return sematable(tablename, typeToComponent[type], columns, config);
  }
}
```

This is what I have on top of my head at the moment. In cases where you dynamic stuff usually you can figure out what type of table you want to show. And then you have some sort of mapping on frontend producing the components based on the `type` provided by the api.

**Comment by pgoldweic** [comment]
Thanks so much for following up and sending that example (it's very useful). I've actually realized that my use case does not *really* require the different sematable instances coexisting after all. The use case is a grading app that can be used for grading multiple sections of a given course. I was at first envisioning that each of the sections would be served by its own instance of MyComponent (same column definitions, only different data would come in, possibly living on different routes), but I'm now leaning towards having just one MyComponent instance that gets populated with different data depending on which course section you are currently working on. Since there's never two tables displaying at any one time, I think that one route that displays this table (MyComponent instance) would likely be enough, as long as it gets populated with the right data - which will be all part of my state's app- when the section is chosen (in a likely different, 'home'-like route). Thanks again for following up on this and for your sample code!
