### ISSUE TITLE
Make possible to distinguish between 'loading' and 'no-data-returned'

### ISSUE THREAD

**Issue by mbonaci** [sematext/sematable#49]
I used spinning wheel as `NoDataComponent` and it works well, but the issue is that it shows whenever there is no data, even when the back end returns empty array or search doesn't find any docs.
So we would need to have both `NoDataComponent` and `LoadingComponent`.
FYI I can implement this (I need it right away).
If I missed something here please provide feedback. 
Thx.

**Comment by otisg** [comment]
I've also observed situations where sematable shows "no data" sort of message, but then a few seconds later the actual data loads.  So +1 for a PR.
