### ISSUE TITLE
Row Selection: Checkbox not centered vertically and (counter) goes to new line

### ISSUE THREAD

**Issue by mbonaci** [sematext/sematable#50]
![image](https://cloud.githubusercontent.com/assets/497926/24876574/7ea6d95a-1e2c-11e7-8c38-8a9515db6242.png)

**Comment by otisg** [comment]
Hm, I thought this was not a sematable bug, but a mistake at the "sematable user" level... no?

**Comment by amir-hadzic** [comment]
Yes, seems like custom checkbox component is used here.
