### ISSUE TITLE
can i use a regular expression as a filter ?!

### ISSUE THREAD

**Issue by EssamTarik** [sematext/sematable#51]

**Comment by otisg** [comment]
Not at the moment, I believe, but that might be interesting.
Out of curiosity, what's your use case?

**Comment by EssamTarik** [comment]
thanks for ur reply
im trying to set a filter using my own text field instead of your component's default search field, so i was trying to make it a real time search (onChange) , the problem is if i set a filter with part of the text it wont work

for example:
if i have a row that contains {name: "foo bar"}
and my search box has "foo"
the filter will be : "name: foo" , and that wont work until my search box has the entire string "foo bar"
