### ISSUE TITLE
Better cosmetics for NN of NN element

### ISSUE THREAD

**Issue by otisg** [sematext/sematable#52]
![screen shot 2017-04-26 at 5 12 52 pm](https://cloud.githubusercontent.com/assets/332580/25457255/b08c5160-2aa3-11e7-9e80-ed5849ce17e3.png)

Would this look and read a little nicer if it:
* didn't have a box/border
* the number (10) was right aligned, so it's closer to "of"
* had up/down arrows to the left of the first number, so that it part after that reads more easily: "10 of 83", without something visual in-between the numbers

**Comment by pgoldweic** [comment]
I would also suggest a word before the drop down, as I believe it was originally? (e.g. 'show' or 'display', or even better, have this be customizable). I've noticed some of my app's users don't find the current style intuitive (they fail to see the connection to the paging size without being told about it).
