### ISSUE TITLE
Add an online demo?

### ISSUE THREAD

**Issue by meitros** [sematext/sematable#65]
Could you add an online demo/example so that one could play with sematable without having to download and run it? It would make it easier for people to see how awesome sematable is :).

**Comment by otisg** [comment]
We could potentially point to https://apps.sematext.com/demo for sematable demo, as there are a number of different sematable instances there.

**Comment by meitros** [comment]
Works for me, thanks!

**Comment by yairEO** [comment]
Well? why isn't this link a part of README? neglecting a demo link won't make this repo any more popular than it already is

**Comment by otisg** [comment]
Done
