### ISSUE TITLE
Custom properties for components?

### ISSUE THREAD

**Issue by fedemarco** [sematext/sematable#67]
Is there a way to send properties to the custom components ?

I have multiple tables, and would like to reuse the custom components, but the data fields names are not always the same, and would like to keep the data untouched.

Thanks

**Comment by amir-hadzic** [comment]
Hello @fedemarco,

Yes, you can use the `componentProps` property of the column to send props to the custom component set with `Component`. `componentProps` can be either an object, or a function. If this is an object, it will simply be passed to the component as props. If this is a function, it should return an object. This object is then passed to the component as props. The function is called with `(row, tableProps)`.
