### ISSUE TITLE
Getting Filtered Data

### ISSUE THREAD

**Issue by sreevisakh** [sematext/sematable#71]
Is there GetFilteredData Selector that I can use to get the search result after applying a filter. GetVisible is only giving the first Page. I am adding Download as excel option so If the user is filtering the data the download should only have Filtered values.

**Comment by mbonaci** [comment]
How about `getFiltered`?
https://github.com/sematext/sematable/blob/c6c89f28de0361c193253d12c6f20763b6c4b720/src/selectors.js#L115

**Comment by sreevisakh** [comment]
Oops. didnt check the code. This is missing in the document section.

**Comment by mbonaci** [comment]
Point taken, added to README.
BTW any plans to contribute the Excel export as a PR?

**Comment by sreevisakh** [comment]
Sure. I will submit the feature.

**Comment by otisg** [comment]
Export to Excel would be a nice contrib, @sreevisakh !

**Comment by megastef** [comment]
This might be helpful: https://www.npmjs.com/package/xlsx

**Comment by sreevisakh** [comment]
Right now I it is constructing a csv file. Since we can just create a string from the data for a csv file. I t will be much simpler. What do you guys think?

**Comment by otisg** [comment]
That seems reasonable to me, since a CSV can be imported by Excel/OpenOffice, too.
