### ISSUE TITLE
Possible to add available actions?

### ISSUE THREAD

**Issue by asteed21** [sematext/sematable#75]
First of all, wanted to say thanks for the awesome job so far. This project is a huge boon for table utility in the React/Redux space. Just wanted to ask - are you guys open to exposing more Sematable actions for use in connected components?

For example, I just ran into a need for using the 'tableSelectAllChanged' action but had to manually adjust the index.js file, whereas the tableDestroyState and tableSetFilter actions seem to be the only  ones currently available by default.

**Comment by amir-hadzic** [comment]
Hi Austin,

I'm glad you find it useful! Yes, we could expose some additional actions.
Any other actions you think would be useful to export by default?
