### ISSUE TITLE
Filter text is not restored from the state

### ISSUE THREAD

**Issue by slavaboiko** [sematext/sematable#88]
Hi,

I don't know if it's related to #9, but when I am experiencing the following behaviour:

1. I filter the table (without pressing Enter, so the *filterText* property is set, but there are no *filter*s
2. I click on the row and navigate to another page in my app
3. I go back in the browser and load the table again
4. I see filtered table, but the filter input is empty (wrong, as I think)
5. So, to see all the table items again, I need to put something in the filter and clear it, which is clearly not very useful.

**Comment by otisg** [comment]
Which version are you using?

**Comment by slavaboiko** [comment]
@otisg 

I'm using version 1.13.0

**Comment by amir-hadzic** [comment]
Hi @slavaboiko. Thanks for reporting this, I'll try to reproduce and fix.
